Introduction

In [8]:
import numpy as np

Creation of arrays

In [12]:
np.array([1, 2, 3])  # one dimensional array

array([1, 2, 3])

In [14]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.full((2, 3), fill_value=7)

array([[7, 7, 7],
       [7, 7, 7]])

In [26]:
np.empty((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [32]:
np.linspace(0, np.pi, 5)  # evenly spaced range with 5 elements

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

Arrays with random elements

In [38]:
np.random.random((3, 4))
# elements are uniformly distributed from half-open interval [0.0, 1.0)

array([[0.00100701, 0.58306146, 0.4310834 , 0.63762916],
       [0.24892343, 0.33021761, 0.60986045, 0.66352794],
       [0.10949322, 0.68871454, 0.60021626, 0.53615571]])

In [40]:
np.random.normal(0, 1 ,(3, 4))
# elements are normally distributed with mean 0 and standard deviation 1

array([[ 0.04826354, -0.77619113,  0.8472708 , -0.36830436],
       [ 1.29713501,  0.3820323 ,  0.72355391, -0.99355874],
       [ 0.01911494, -0.59202338, -0.43638781, -1.83356192]])

In [54]:
np.random.randint(-2, 10, (3, 4))
# elements are uniformly distributed integers from the half-open interval [-2, 10)

array([[ 0,  9, -2,  1],
       [ 3,  7,  8,  2],
       [ 9,  2,  4,  2]])

In [46]:
np.random.seed(0)
print(np.random.randint(0, 100, 10))
print(np.random.normal(0, 1, 10))

[44 47 64 67 67  9 83 21 36 87]
[ 1.26611853 -0.50587654  2.54520078  1.08081191  0.48431215  0.57914048
 -0.18158257  1.41020463 -0.37447169  0.27519832]


In [56]:
new_generator = np.random.RandomState(seed=123)
# RandomState is a class, so we give the seed to its constructor
new_generator.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

Array types and attributes