Introduction

In [8]:
import numpy as np

Creation of arrays

In [12]:
np.array([1, 2, 3])  # one dimensional array

array([1, 2, 3])

In [14]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.full((2, 3), fill_value=7)

array([[7, 7, 7],
       [7, 7, 7]])

In [26]:
np.empty((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [32]:
np.linspace(0, np.pi, 5)  # evenly spaced range with 5 elements

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

Arrays with random elements

In [38]:
np.random.random((3, 4))
# elements are uniformly distributed from half-open interval [0.0, 1.0)

array([[0.00100701, 0.58306146, 0.4310834 , 0.63762916],
       [0.24892343, 0.33021761, 0.60986045, 0.66352794],
       [0.10949322, 0.68871454, 0.60021626, 0.53615571]])

In [40]:
np.random.normal(0, 1 ,(3, 4))
# elements are normally distributed with mean 0 and standard deviation 1

array([[ 0.04826354, -0.77619113,  0.8472708 , -0.36830436],
       [ 1.29713501,  0.3820323 ,  0.72355391, -0.99355874],
       [ 0.01911494, -0.59202338, -0.43638781, -1.83356192]])

In [54]:
np.random.randint(-2, 10, (3, 4))
# elements are uniformly distributed integers from the half-open interval [-2, 10)

array([[ 0,  9, -2,  1],
       [ 3,  7,  8,  2],
       [ 9,  2,  4,  2]])

In [46]:
np.random.seed(0)
print(np.random.randint(0, 100, 10))
print(np.random.normal(0, 1, 10))

[44 47 64 67 67  9 83 21 36 87]
[ 1.26611853 -0.50587654  2.54520078  1.08081191  0.48431215  0.57914048
 -0.18158257  1.41020463 -0.37447169  0.27519832]


In [56]:
new_generator = np.random.RandomState(seed=123)
# RandomState is a class, so we give the seed to its constructor
new_generator.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

Array types and attributes

In [64]:
def info(name, a):
    print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size}, and dtype {a.dtype}:")
    print(a)

In [66]:
b = np.array([[1, 2, 3], [4, 5, 6]])
info("b", b)

b has dim 2, shape (2, 3), size 6, and dtype int64:
[[1 2 3]
 [4 5 6]]


In [68]:
c = np.array([b, b])  # creates a 3-d array
info("c", c)

c has dim 3, shape (2, 2, 3), size 12, and dtype int64:
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [70]:
d = np.array([[1, 2, 3, 4]])  # a row vector
info("d", d)

d has dim 2, shape (1, 4), size 4, and dtype int64:
[[1 2 3 4]]


Indexing, slicing, and reshaping

Indexing

In [76]:
a = np.array([1, 4, 2, 7, 9, 5])
print(a[1])
print(a[-2])

4
9


In [78]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b[1, 2])   # row index 1, column index 2
print(b[0, -1])  # row index 0, column index -1

[[1 2 3]
 [4 5 6]]
6
3


In [80]:
# as with lists, modification through indexing is possible
b[0, 0] = 10
print(b)

[[10  2  3]
 [ 4  5  6]]


In [82]:
print(b[0])  # first row
print(b[1])  # second row

[10  2  3]
[4 5 6]


Slicing

In [85]:
print(a)
print(a[1:3])
print(a[::-1])  # reverses the array

[1 4 2 7 9 5]
[4 2]
[5 9 7 2 4 1]


In [87]:
print(b)
print(b[:,0])
print(b[0,:])
print(b[:,1:])

[[10  2  3]
 [ 4  5  6]]
[10  4]
[10  2  3]
[[2 3]
 [5 6]]


In [89]:
b[:,1:] = 7
print(b)

[[10  7  7]
 [ 4  7  7]]


In [91]:
print(b[:,0])  # first column
print(b[1,:])  # second row

[10  4]
[4 7 7]


Reshaping

In [96]:
a = np.arange(9)
anew = a.reshape(3, 3)
info("anew", anew)
info("a", a)

anew has dim 2, shape (3, 3), size 9, and dtype int64:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
a has dim 1, shape (9,), size 9, and dtype int64:
[0 1 2 3 4 5 6 7 8]


In [98]:
d = np.arange(4)      # 1d array
dr = d.reshape(1, 4)  # row vector
dc = d.reshape(4, 1)  # column vector
info("d", d)
info("dr", dr)
info("dc", dc)

d has dim 1, shape (4,), size 4, and dtype int64:
[0 1 2 3]
dr has dim 2, shape (1, 4), size 4, and dtype int64:
[[0 1 2 3]]
dc has dim 2, shape (4, 1), size 4, and dtype int64:
[[0]
 [1]
 [2]
 [3]]


In [100]:
info("d", d)
info("drow", d[:, np.newaxis])
info("drow", d[np.newaxis, :])
info("dcol", d[:, np.newaxis])

d has dim 1, shape (4,), size 4, and dtype int64:
[0 1 2 3]
drow has dim 2, shape (4, 1), size 4, and dtype int64:
[[0]
 [1]
 [2]
 [3]]
drow has dim 2, shape (1, 4), size 4, and dtype int64:
[[0 1 2 3]]
dcol has dim 2, shape (4, 1), size 4, and dtype int64:
[[0]
 [1]
 [2]
 [3]]


Exercise 2.11 (rows and columns)

In [103]:
a = np.random.randint(0, 10, (4,4))
print(a)
print(a.T)

[[4 3 4 4]
 [8 4 3 7]
 [5 5 0 1]
 [5 9 3 0]]
[[4 8 5 5]
 [3 4 5 9]
 [4 3 0 3]
 [4 7 1 0]]


My solution:

In [106]:
import numpy as np

def get_rows(a):
    """Returns list of rows of a 2D array"""
    b, c = a.shape
    return [ np.array(a[i]) for i in range(b) ]

def get_columns(a):
    """Returns list of columns of a 2D array"""
    b, c = a.shape
    return [ np.array(a[:,i]) for i in range(c) ]

def main():
    np.random.seed(0)
    a=np.random.randint(0,10, (4,4))
    print("a:", a)
    print("Rows:", get_rows(a))
    print("Columns:", get_columns(a))

if __name__ == "__main__":
    main()

a: [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
Rows: [array([5, 0, 3, 3]), array([7, 9, 3, 5]), array([2, 4, 7, 6]), array([8, 8, 1, 6])]
Columns: [array([5, 7, 2, 8]), array([0, 9, 4, 8]), array([3, 3, 7, 1]), array([3, 5, 6, 6])]


Suggested solution:

In [109]:
import numpy as np
 
def get_rows(a):
    result = [row for row in a]
    return result
 
def get_columns(a):
    result = [row for row in a.T]
    return result
 
def main():
    np.random.seed(0)
    a=np.random.randint(0,10, (4,4))
    print("a:", a)
    print("Rows:", get_rows(a))
    print("Columns:", get_columns(a))
 
if __name__ == "__main__":
    main()

a: [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
Rows: [array([5, 0, 3, 3]), array([7, 9, 3, 5]), array([2, 4, 7, 6]), array([8, 8, 1, 6])]
Columns: [array([5, 7, 2, 8]), array([0, 9, 4, 8]), array([3, 3, 7, 1]), array([3, 5, 6, 6])]


In [129]:
# why the suggested solution works
a = np.array([[1, 2, 3], [4, 5, 6]])
for i in a:
    print(i)

[1 2 3]
[4 5 6]


Array concatenation, splitting and stacking

In [135]:
a = np.arange(2)
b = np.arange(2, 5)
print(f"a has shape {a.shape}: {a}")
print(f"b has shape {b.shape}: {b}")
np.concatenate((a, b))  # concatenating 1d arrays

a has shape (2,): [0 1]
b has shape (3,): [2 3 4]


array([0, 1, 2, 3, 4])

In [147]:
c = np.arange(1, 5).reshape(2, 2)
print(f"c has shape {c.shape}:", c, sep="\n")
np.concatenate((c, c))  # concatenating 2d arrays

c has shape (2, 2):
[[1 2]
 [3 4]]


array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [141]:
np.concatenate((c, c), axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [143]:
print("New row:")
print(np.concatenate((c, a.reshape(1, 2))))
print("New column:")
print(np.concatenate((c, a.reshape(2, 1)), axis=1))

New row:
[[1 2]
 [3 4]
 [0 1]]
New column:
[[1 2 0]
 [3 4 1]]


In [149]:
np.stack((b, b))

array([[2, 3, 4],
       [2, 3, 4]])

In [151]:
np.stack((b, b), axis=1)

array([[2, 2],
       [3, 3],
       [4, 4]])

In [153]:
d = np.arange(12).reshape(6, 2)
print("d:")
print(d)
d1, d2 = np.split(d, 2)
print("d1:")
print(d1)
print("d2:")
print(d2)

d:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
d1:
[[0 1]
 [2 3]
 [4 5]]
d2:
[[ 6  7]
 [ 8  9]
 [10 11]]


In [155]:
d = np.arange(12).reshape(2, 6)
print("d:")
print(d)
parts = np.split(d, (2, 3, 5), axis=1)
for i, p in enumerate(parts):
    print("part %i:" %i)
    print(p)

d:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
part 0:
[[0 1]
 [6 7]]
part 1:
[[2]
 [8]]
part 2:
[[ 3  4]
 [ 9 10]]
part 3:
[[ 5]
 [11]]


Exercise 2.12 (row and column vectors)

My solution:

In [159]:
import numpy as np

def get_row_vectors(a):
    """Returns list of rows shape (1,m) from input array shape (n,m)"""
    n, m = a.shape
    return [ row.reshape(1, m) for row in a ]

def get_column_vectors(a):
    """Returns list of columns shape (n,1) from input array shape (n,m)"""
    n, m = a.shape
    return [ row.reshape(n, 1) for row in a.T ]

def main():
    np.random.seed(0)
    a=np.random.randint(0,10, (4,4))
    print("a:", a)
    print("Row vectors:", get_row_vectors(a))
    print("Column vectors:", get_column_vectors(a))

if __name__ == "__main__":
    main()

a: [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
Row vectors: [array([[5, 0, 3, 3]]), array([[7, 9, 3, 5]]), array([[2, 4, 7, 6]]), array([[8, 8, 1, 6]])]
Column vectors: [array([[5],
       [7],
       [2],
       [8]]), array([[0],
       [9],
       [4],
       [8]]), array([[3],
       [3],
       [7],
       [1]]), array([[3],
       [5],
       [6],
       [6]])]


Suggested solution:

In [162]:
import numpy as np
 
def get_row_vectors(a):
    return np.split(a, a.shape[0], axis=0)
 
def get_column_vectors(a):
    return np.split(a, a.shape[1], axis=1)
 
def main():
    np.random.seed(0)
    a=np.random.randint(0,10, (4,4))
    print("a:", a)
    print("Row vectors:", get_row_vectors(a))
    print("Column vectors:", get_column_vectors(a))
 
if __name__ == "__main__":
    main()

a: [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
Row vectors: [array([[5, 0, 3, 3]]), array([[7, 9, 3, 5]]), array([[2, 4, 7, 6]]), array([[8, 8, 1, 6]])]
Column vectors: [array([[5],
       [7],
       [2],
       [8]]), array([[0],
       [9],
       [4],
       [8]]), array([[3],
       [3],
       [7],
       [1]]), array([[3],
       [5],
       [6],
       [6]])]


Exercise 2.13 (diamond)

My solution:

In [204]:
import numpy as np

def diamond(n):
    """Returns 2D integer array where 1s form diamond shape,
    rest of numbers are 0, n is the length of side of diamond"""
    # identity matrix and its reverse
    a = np.eye(2*n-1, dtype=int)
    b = a[::-1]

    c = b[n-1:,:n]  # upper left
    d = a[:n,1:n]  # upper right
    f = np.concatenate((c, d), axis=1)  # upper half

    g = a[1:n,:n]  # bottom left
    h = b[1:n,n:]  # bottom right
    m = np.concatenate((g, h), axis=1)  # bottom half
        
    p = np.concatenate((f, m))  # combine upper and bottom
    return p

'''
Reference matrices for n = 4

Result:
[[0 0 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 0 0 1 0]
 [1 0 0 0 0 0 1]
 [0 1 0 0 0 1 0]
 [0 0 1 0 1 0 0]
 [0 0 0 1 0 0 0]]

a:
[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]

b:
[[0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
'''

def main():
    print(diamond(1))
    print(diamond(2))
    print(diamond(3))
    print(diamond(4))
    print(diamond(5))

if __name__ == "__main__":
    main()

[[1]]
[[0 1 0]
 [1 0 1]
 [0 1 0]]
[[0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]
[[0 0 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 0 0 1 0]
 [1 0 0 0 0 0 1]
 [0 1 0 0 0 1 0]
 [0 0 1 0 1 0 0]
 [0 0 0 1 0 0 0]]
[[0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 1 0 0 0]
 [0 0 1 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 1 0 0]
 [0 0 0 1 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0]]


Suggested solution:

In [180]:
import numpy as np
 
def diamond(n):
    e=np.eye(n, dtype=int)  # identity (n, n)

    # upper left is reverse identity, upper right is identity bar 1st row
    a=np.concatenate([e[::-1], e[:,1:]], axis=1)

    # take upper bar last row and combine with its inverse
    result = np.concatenate([a[:-1], a[::-1]], axis=0)
    return result
 
def main():
    print(diamond(3))
 
if __name__ == "__main__":
    main()

[[0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]


Fast computation using universal functions

In [208]:
L = [1, 5.2, "ab"]
L2 = []
for x in L:
    L2.append(x*2)
print(L2)

[2, 10.4, 'abab']


In [210]:
a = np.array([2.1, 5.0, 17.2])
a2 = a*2
print(a2)

[ 4.2 10.  34.4]


In [212]:
b = np.array([-1, 3.2, 2.4])
print(-a**2 * b)

[   4.41   -80.    -710.016]


In [214]:
print(np.abs(b))
print(np.cos(b))
print(np.exp(b))
print(np.log2(np.abs(b)))

[1.  3.2 2.4]
[ 0.54030231 -0.99829478 -0.73739372]
[ 0.36787944 24.5325302  11.02317638]
[0.         1.67807191 1.26303441]


Aggregations: max, min, sum, mean, standard deviation and more

In [217]:
np.random.seed(0)
a = np.random.randint(-100, 100, (4, 5))
print(a)
print(f"Minimum: {a.min()}, maximum: {a.max()}")
print(f"Sum: {a.sum()}")
print(f"Mean: {a.mean()}, standard deviation: {a.std()}")

[[ 72 -53  17  92 -33]
 [ 95   3 -91 -79 -64]
 [-13 -30 -12  40 -42]
 [ 93 -61 -13  74 -12]]
Minimum: -91, maximum: 95
Sum: -17
Mean: -0.85, standard deviation: 58.39886557117355


In [219]:
np.random.seed(9)
b = np.random.randint(0, 10, (3, 4))
print(b)
print("Column sums:", b.sum(axis=0))
print("Row sums:", b.sum(axis=1))

[[5 6 8 6]
 [1 6 4 8]
 [1 8 5 1]]
Column sums: [ 7 20 17 15]
Row sums: [25 19 15]


In [227]:
a = np.arange(1000)
%timeit np.sum(a)

1.42 μs ± 8.93 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [225]:
%timeit sum(a)

40.2 μs ± 1.75 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Exercise 2.14 (vector lengths)

My solution:

In [236]:
import numpy as np
#import scipy.linalg

def vector_lengths(a):
    """Returns array with length of each row vector in input array"""
    return np.sqrt((a**2).sum(axis=1))

def main():
    test = np.random.randint(-10, 10, (4, 3))
    print(test)
    print(vector_lengths(test))

if __name__ == "__main__":
    main()

[[-1  6  7]
 [-2  3 -9]
 [ 3  2  8]
 [-2 -6 -7]]
[9.2736185  9.69535971 8.77496439 9.43398113]


Suggested solution:

In [234]:
import numpy as np
#import scipy.linalg
 
def vector_lengths(a):
    #return scipy.linalg.norm(a, 2, axis=1)
    return np.sqrt(np.sum(a**2, axis=1))
 
def main():
    a = np.asarray([[1, 2], [3, 4], [5, 6]])
    print("a:", a)
    print("Lengths:", vector_lengths(a))
 
if __name__ == "__main__":
    main()

a: [[1 2]
 [3 4]
 [5 6]]
Lengths: [2.23606798 5.         7.81024968]


Exercise 2.15 (vector angles)

In [244]:
import numpy as np

def vector_angles(X, Y):
    """Returns angle between row vectors in degrees"""
    ip = np.sum(X*Y)  # inner product
    xm = np.sqrt(np.sum(X**2, axis=1))  # magnitude of X
    ym = np.sqrt(np.sum(Y**2, axis=1))  # magnitude of Y
    rhs = (ip)/(xm*ym)
    clipped = np.clip(rhs, -1, 1)
    rad = np.arccos(clipped)
    return rad * (180/np.pi)  # convert from radian to degrees

def main():
    test1 = np.random.randint(-10, 10, (2, 2))
    test2 = np.random.randint(-10, 10, (2, 2))
    print(vector_angles(test1, test2))

if __name__ == "__main__":
    main()

[180.         141.46015129]


Broadcasting

In [247]:
np.arange(3) + np.array([4])

array([4, 5, 6])

In [249]:
np.arange(3) + 4

array([4, 5, 6])

In [251]:
a = np.full((3,3), 5)
b = np.arange(3)
print("a:", a, sep="\n")
print("b:", b)
print("a+b:", a+b, sep="\n")

a:
[[5 5 5]
 [5 5 5]
 [5 5 5]]
b: [0 1 2]
a+b:
[[5 6 7]
 [5 6 7]
 [5 6 7]]


In [253]:
# b was first broadcasted to this array
np.array([[0, 1, 2], [0, 1, 2], [0, 1, 2]])
# and then addition was performed

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [255]:
a = np.arange(3)
b = np.arange(3).reshape((3, 1))
info("a", a)
info("b", b)
info("a+b", a+b)

a has dim 1, shape (3,), size 3, and dtype int64:
[0 1 2]
b has dim 2, shape (3, 1), size 3, and dtype int64:
[[0]
 [1]
 [2]]
a+b has dim 2, shape (3, 3), size 9, and dtype int64:
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [257]:
broadcasted_a, broadcasted_b = np.broadcast_arrays(a, b)
info("broadcasted_a", broadcasted_a)
info("broadcasted_b", broadcasted_b)

broadcasted_a has dim 2, shape (3, 3), size 9, and dtype int64:
[[0 1 2]
 [0 1 2]
 [0 1 2]]
broadcasted_b has dim 2, shape (3, 3), size 9, and dtype int64:
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [263]:
a = np.array([1, 2, 3])
b = np.array([4, 5])
try:
    a+b  # this doesn't work since it violates rule 3
    # dimension must either match or have value of 1 
except ValueError as e:
    import sys
    print(e, file=sys.stderr)

operands could not be broadcast together with shapes (3,) (2,) 


Exercise 2.16 (multiplication table revisited)

My solution:

In [275]:
import numpy as np

def multiplication_table(n):
    """Returns multiplictaion table as an array with shape (n, n)"""
    r = np.arange(n).reshape(n, 1)  # rows value
    c = np.arange(n)  # columns value shape (1, n)
    return r*c  # broadcast so each value becomes product of row times column

def main():
    print(multiplication_table(4))

if __name__ == "__main__":
    main()

[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]


Suggested solution:

In [270]:
import numpy as np
 
def multiplication_table(n):
    a=np.arange(n)
    return a[:, np.newaxis] * a[np.newaxis, :]
 
def main():
    print(multiplication_table(4))
 
if __name__ == "__main__":
    main()

[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
